module.exports.createPackageJson = ({ projectName }) => {
  const configObj = {
    name: projectName.toLowerCase(),
    version: "1.0.0",
    description: "App generated by @jalasem/create-node-app",
    main: "index.js",
    scripts: {
      test: 'echo "Error: no test specified" && exit 1',
    },
    repository: {
      type: "git",
      url: "https://repo.url",
    },
    keywords: [],
    author: "",
    license: "ISC",
    bugs: {
      url: "https://repo.url/issues",
    },
    homepage: "https://repo.url#readme",
  };

  return JSON.stringify(configObj, null, 2);
};
